global:
  scrape_interval: 120s # Default scrape interval

scrape_configs:


  - job_name: "strapi"
    metrics_path: "/api/metrics"
    scheme: https
    static_configs:
      - targets: [ "nexus-back.up.railway.app" ]
  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE